---
# tasks file for grafana
- name: create grafana dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ grafana_data_dir }}"
    - "{{ grafana_config_dir }}"
    - "{{ grafana_plugins_dir }}"
  tags:
    - grafana
    - grafana_dirs
    - grafana_install

- name: set grafana.ini conf
  template:
    src: grafana.ini.j2
    dest: "{{ grafana_config_dir }}/grafana.ini"
    mode: '0644'
  notify: restart grafana
  tags:
    - grafana
    - grafana_install
    - grafana_config

- name: set rules on dirs
  file:
    path: "{{ item }}"
    owner: "{{ grafana_uid | string }}"
    group: "{{ grafana_gid | string }}"
    recurse: yes
  loop:
    - "{{ grafana_data_dir }}"
    - "{{ grafana_plugins_dir }}"
  tags:
    - grafana
    - grafana_install

- name: set rules on config
  file:
    path: "{{ grafana_config_dir }}/grafana.ini"
    owner: "{{ grafana_uid | string }}"
    group: "{{ grafana_gid | string }}"
    mode: '0644'
  tags:
    - grafana
    - grafana_install

- name: start systemd unit for grafana
  template:
    src: grafana.service.j2
    dest: "/etc/systemd/system/{{ grafana_container_name }}.service"
    mode: '0644'
  notify:
    - reload systemd
    - restart grafana
  tags:
    - grafana
    - grafana_config
    - grafana_install

- name: start and enabled grafana
  systemd:
    name: "{{ grafana_container_name }}"
    state: started
    enabled: yes
    daemon_reload: yes
  tags:
    - grafana
    - grafana_service
    - grafana_install

# Stopping grafana service
- name: stop grafana
  systemd:
    name: "{{ grafana_container_name }}"
    state: stopped
    enabled: no
  tags:
    - grafana_stop
    - never

# Deleting grafana service without data
- name: delete grafana container
  command:
    cmd: "docker rm -f {{ grafana_container_name }}"
  register: remove_container # Set register on task
  failed_when: false # If docker rm down with error, that task will continue to be executed
  changed_when: remove_container.rc == 0
  tags:
    - grafana_remove
    - never

- name: delete systemd unit grafana
  file:
    path: "/etc/systemd/system/{{ grafana_container_name }}.service"
    state: absent
  notify: reload systemd
  tags:
    - grafana_remove
    - never

# This task works by analogy with "delete grafana container" task
- name: delete grafana image
  command:
    cmd: "docker rmi {{ grafana_image_full }}"
  register: remove_image
  failed_when: false
  changed_when: remove_image.rc == 0
  tags:
    - grafana_remove_image
    - never

# Full removal
- name: delete grafana dirs
  file:
    path: "{{ grafana_dir }}"
    state: absent
  tags:
    - grafana_purge
    - never
