---
- name: Install Docker
  hosts: all
  become: true
  roles: 
    - role: docker

#- name: Install Node-Exporter
#  hosts: target-servers
#  become: true
#  roles:
#    - role: node-exporter

- name: Install and run GAP
  hosts: monitoring-servers
  become: true
  roles:
    - role: prometheus
    - role: grafana
    - role: alertmanager
