---
# defaults file for node_exporter
node_exporter_image: "prom/node-exporter"
node_exporter_image_tag: "v1.11.1"
node_exporter_image_full: "{{ node_exporter_image }}:{{ node_exporter_image_tag }}"
node_exporter_port: 9100

node_exporter_container_name: node-exporter
node_exporter_restart_policy: always
