---
# tasks file for prometheus
- name: create prometheus dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ prometheus_data_dir }}"
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_config_dir }}/rules"
  tags:
    - prometheus_dirs
    - prometheus_install

- name: set prometheus.yml conf
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    mode: '0644'
  notify: restart prometheus
  tags:
    - prometheus_config
    - prometheus_install

- name: set alert rules
  template:
    src: node_alerts.yml.j2
    dest: "{{ prometheus_config_dir }}/rules/node_alerts.yml"
    mode: '0644'
  notify: restart prometheus
  tags:
    - prometheus_config
    - prometheus_install

- name: set rules on dirs
  file:
    path: "{{ item }}"
    owner: "{{ prometheus_uid | string }}"
    group: "{{ prometheus_gid | string }}"
    recurse: yes
  loop:
    - "{{ prometheus_data_dir }}"
    - "{{ prometheus_config_dir }}"
  tags:
    - prometheus_install

- name: set rules on config
  file:
    path: "{{ prometheus_config_dir }}/prometheus.yml"
    owner: "{{ prometheus_uid | string }}"
    group: "{{ prometheus_gid | string }}"
    mode: '0644'
  tags:
    - prometheus_install

- name: start systemd unit prometheus
  template:
    src: prometheus.service.j2
    dest: "/etc/systemd/system/{{ prometheus_container_name }}.service"
    mode: '0644'
  notify:
    - reload systemd
    - restart prometheus
  tags:
    - prometheus_service
    - prometheus_install

- name: start and enabled prometheus
  systemd:
    name: "{{ prometheus_container_name }}"
    state: started
    enabled: yes
    daemon_reload: yes
  tags:
    - prometheus_service
    - prometheus_install

# Stopping prometheus service
- name: stop prometheus
  systemd:
    name: "{{ prometheus_container_name }}"
    state: stopped
    enabled: no
  tags:
    - prometheus_stop
    - purge # tag for full deleting GAP
    - never

# Deleting prometheus service without data
- name: delete prometheus container
  command:
    cmd: "docker rm -f {{ prometheus_container_name }}"
  register: remove_container # Set register on task
  failed_when: false # If docker rm down with error, that task will continue to be executed
  changed_when: remove_container.rc == 0
  tags:
    - prometheus_remove
    - purge
    - never

- name: delete systemd unit prometheus
  file:
    path: "/etc/systemd/system/{{ prometheus_container_name }}.service"
    state: absent
  notify: reload systemd
  tags:
    - prometheus_remove
    - purge
    - never

# This task works by analogy with "delete prometheus container" task
- name: delete prometheus image
  command:
    cmd: "docker rmi {{ prometheus_image_full }}"
  register: remove_image
  failed_when: false
  changed_when: remove_image.rc == 0
  tags:
    - prometheus_remove_image
    - purge
    - never

# Full removal
- name: delete prometheus dirs
  file:
    path: "{{ prometheus_dir }}"
    state: absent
  tags:
    - prometheus_purge
    - purge
    - never
