---
# tasks file for docker
#
# ========= Debian/Ubuntu =========
- name: check if docker is already installed
  command: docker --version
  register: docker_check
  failed_when: false
  changed_when: false

- name: skip docker installation
  debug:
    msg: "Docker is already installed, skipping..."
  when: docker_check.rc == 0

- name: install docker (debian family)
  block:
    - name: install dependencies
      apt:
        name: "{{ docker_dependencies }}"
        state: "{{ docker_dependencies_state }}"
        update_cache: yes
      retries: 3
      delay: 5

    - name: create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: add docker gpg key
      get_url:
        url: "{{ docker_apt_gpg_key}}"
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
      retries: 3
      delay: 5

    - name: add docker repo
      apt_repository:
        repo: "deb [arch={{ ansible_architecture | replace('x86_64', 'amd64') | replace('aarch64', 'arm64') }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: "{{ docker_repo_state }}"
        update_cache: yes
      retries: 3
      delay: 5

    - name: install docker packages
      apt:
        name: "{{ docker_packages }}"
        state: "{{ docker_packages_state }}"
        update_cache: yes
      retries: 3
      delay: 5

  when:
    - ansible_facts['os_family'] == "Debian"
    - docker_check.rc != 0

# ========= RHEL =========
- name: install docker (RHEL)
  ansible.builtin.dnf:
    name: "{{ docker_packages }}"
    state: present
  when: ansible_facts['os_family'] == "RedHat"

# Common to all OS
- name: ensure docker running and enabled
  service:
    name: docker
    state: started
    enabled: yes

- name: ensure docker group exists
  group:
    name: docker
    state: present

- name: adding user to docker group
  user:
    name: "{{ monitoring_user }}"
    groups: docker
    append: yes
  notify: restart docker

- name: restart docker service
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
